[package]
name = "shapley"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "shapley"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.98"
maplit = "1.0.2"
pyo3 = "0.25.0"
statrs = "0.18.0"
