__version__: str = ...
"""The version of shapleyrs."""


class Shapley:
    def __init__(self, players: list[int], coalition_worth: dict[tuple[int, ...], float]) -> None: ...
    def shapley_value(self, player: int) -> float: ...
